export const Moves: {[k: string]: ModdedMoveData} = {
    pound: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 100,
    },
    karatechop: {
        inherit: true,
        basePower: 90,
        pp: 25,
        accuracy: 100,
    },
    doubleslap: {
        inherit: true,
        basePower: 20,
        pp: 15,
        accuracy: 60,
    },
    cometpunch: {
        inherit: true,
        basePower: 30,
        pp: 10,
        accuracy: 100,
    },
    machpunch: {
        inherit: true,
        basePower: 30,
        pp: 5,
        accuracy: 95,
    },
    payday: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 100,
    },
    firepunch: {
        inherit: true,
        basePower: 95,
        pp: 15,
        accuracy: 95,
    },
    icepunch: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 95,
    },
    thunderpunch: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 85,
    },
    scratch: {
        inherit: true,
        basePower: 85,
        pp: 40,
        accuracy: 100,
    },
    agarre: {
        inherit: true,
        basePower: 50,
        pp: 15,
        accuracy: 100,
    },
    guillotina: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 20,
    },
    vcortante: {
        inherit: true,
        basePower: 85,
        pp: 20,
        accuracy: 100,
    },
    danzaespada: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    corte: {
        inherit: true,
        basePower: 50,
        pp: 15,
        accuracy: 70,
    },
    tornado: {
        inherit: true,
        basePower: 75,
        pp: 30,
        accuracy: 100,
    },
    ataqueala: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 95,
    },
    remolino: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 100,
    },
    vuelo: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 90,
    },
    atadura: {
        inherit: true,
        basePower: 50,
        pp: 30,
        accuracy: 90,
    },
    portazo: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 80,
    },
    ltigocepa: {
        inherit: true,
        basePower: 85,
        pp: 25,
        accuracy: 95,
    },
    pisotn: {
        inherit: true,
        basePower: 95,
        pp: 15,
        accuracy: 95,
    },
    doblepatada: {
        inherit: true,
        basePower: 70,
        pp: 25,
        accuracy: 95,
    },
    megapatada: {
        inherit: true,
        basePower: 115,
        pp: 25,
        accuracy: 100,
    },
    jumpkick: {
        inherit: true,
        basePower: 140,
        pp: 25,
        accuracy: 90,
    },
    patadagiro: {
        inherit: true,
        basePower: 65,
        pp: 5,
        accuracy: 90,
    },
    ataquearena: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 95,
    },
    golpecabeza: {
        inherit: true,
        basePower: 90,
        pp: 15,
        accuracy: 85,
    },
    cornada: {
        inherit: true,
        basePower: 60,
        pp: 40,
        accuracy: 95,
    },
    ataquefuria: {
        inherit: true,
        basePower: 25,
        pp: 15,
        accuracy: 95,
    },
    perforador: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 50,
    },
    placaje: {
        inherit: true,
        basePower: 140,
        pp: 25,
        accuracy: 100,
    },
    golpecuerpo: {
        inherit: true,
        basePower: 100,
        pp: 40,
        accuracy: 95,
    },
    repeticin: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 65,
    },
    derribo: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 70,
    },
    golpe: {
        inherit: true,
        basePower: 20,
        pp: 25,
        accuracy: 95,
    },
    doblefilo: {
        inherit: true,
        basePower: 100,
        pp: 20,
        accuracy: 90,
    },
    ltigo: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 85,
    },
    picotazoven: {
        inherit: true,
        basePower: 65,
        pp: 30,
        accuracy: 100,
    },
    dobleataque: {
        inherit: true,
        basePower: 40,
        pp: 20,
        accuracy: 85,
    },
    pinmisil: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 65,
    },
    malicioso: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    mordisco: {
        inherit: true,
        basePower: 80,
        pp: 40,
        accuracy: 95,
    },
    gruido: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    rugido: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    canto: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 20,
    },
    supersnico: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 85,
    },
    bombasnica: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 100,
    },
    anulacin: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 75,
    },
    cido: {
        inherit: true,
        basePower: 25,
        pp: 25,
        accuracy: 85,
    },
    ascuas: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 70,
    },
    lanzallamas: {
        inherit: true,
        basePower: 70,
        pp: 15,
        accuracy: 100,
    },
    neblina: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 0,
    },
    pistolaagua: {
        inherit: true,
        basePower: 145,
        pp: 20,
        accuracy: 85,
    },
    hidrobomba: {
        inherit: true,
        basePower: 75,
        pp: 40,
        accuracy: 90,
    },
    surf: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 100,
    },
    rayohielo: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 95,
    },
    ventisca: {
        inherit: true,
        basePower: 95,
        pp: 40,
        accuracy: 95,
    },
    psicorrayo: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 100,
    },
    rayoburbuja: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 100,
    },
    rayoaurora: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 65,
    },
    hiperrayo: {
        inherit: true,
        basePower: 65,
        pp: 25,
        accuracy: 100,
    },
    peck: {
        inherit: true,
        basePower: 145,
        pp: 25,
        accuracy: 100,
    },
    picotaladro: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 100,
    },
    sumisin: {
        inherit: true,
        basePower: 95,
        pp: 25,
        accuracy: 45,
    },
    patadabaja: {
        inherit: true,
        basePower: 1,
        pp: 15,
        accuracy: 75,
    },
    contador: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 100,
    },
    movssmico: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 100,
    },
    strength: {
        inherit: true,
        basePower: 150,
        pp: 15,
        accuracy: 100,
    },
    absorber: {
        inherit: true,
        basePower: 70,
        pp: 15,
        accuracy: 90,
    },
    megaagotar: {
        inherit: true,
        basePower: 105,
        pp: 10,
        accuracy: 90,
    },
    drenadoras: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 75,
    },
    desarrollo: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 0,
    },
    hojaafilada: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 95,
    },
    rayosolar: {
        inherit: true,
        basePower: 65,
        pp: 40,
        accuracy: 100,
    },
    polvoveneno: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    paralizador: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 80,
    },
    somnfero: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 95,
    },
    danzaptalo: {
        inherit: true,
        basePower: 90,
        pp: 15,
        accuracy: 85,
    },
    dispdemora: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    furiadragn: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 100,
    },
    girofuego: {
        inherit: true,
        basePower: 55,
        pp: 10,
        accuracy: 95,
    },
    impactrueno: {
        inherit: true,
        basePower: 70,
        pp: 15,
        accuracy: 95,
    },
    rayo: {
        inherit: true,
        basePower: 135,
        pp: 25,
        accuracy: 100,
    },
    ondatrueno: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    trueno: {
        inherit: true,
        basePower: 75,
        pp: 25,
        accuracy: 100,
    },
    lanzarrocas: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 100,
    },
    terremoto: {
        inherit: true,
        basePower: 80,
        pp: 15,
        accuracy: 95,
    },
    fisura: {
        inherit: true,
        basePower: 1,
        pp: 30,
        accuracy: 45,
    },
    excavar: {
        inherit: true,
        basePower: 65,
        pp: 15,
        accuracy: 90,
    },
    txico: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    confusin: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 95,
    },
    psquico: {
        inherit: true,
        basePower: 115,
        pp: 40,
        accuracy: 100,
    },
    hipnosis: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    meditacin: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    agilidad: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    atrpido: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 100,
    },
    furia: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 90,
    },
    teletransp: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    tinieblas: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 90,
    },
    mimtico: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    chirrido: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    dobleequipo: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    recuperacin: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    fortaleza: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    reduccin: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 0,
    },
    pantallahumo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    rayoconfuso: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 80,
    },
    refugio: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    rizodefensa: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    barrera: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 0,
    },
    pantallaluz: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 0,
    },
    niebla: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    reflejo: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    focoenerga: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    venganza: {
        inherit: true,
        basePower: 1,
        pp: 15,
        accuracy: 85,
    },
    metrnomo: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 0,
    },
    movespejo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    autodestruc: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 95,
    },
    bombahuevo: {
        inherit: true,
        basePower: 90,
        pp: 25,
        accuracy: 75,
    },
    lick: {
        inherit: true,
        basePower: 100,
        pp: 20,
        accuracy: 100,
    },
    polucin: {
        inherit: true,
        basePower: 55,
        pp: 30,
        accuracy: 75,
    },
    residuos: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 90,
    },
    boneclub: {
        inherit: true,
        basePower: 100,
        pp: 40,
        accuracy: 100,
    },
    llamarada: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 90,
    },
    cascada: {
        inherit: true,
        basePower: 95,
        pp: 15,
        accuracy: 85,
    },
    tenaza: {
        inherit: true,
        basePower: 55,
        pp: 5,
        accuracy: 80,
    },
    rapidez: {
        inherit: true,
        basePower: 70,
        pp: 35,
        accuracy: 0,
    },
    cabezazo: {
        inherit: true,
        basePower: 80,
        pp: 15,
        accuracy: 85,
    },
    clavocan: {
        inherit: true,
        basePower: 40,
        pp: 15,
        accuracy: 100,
    },
    restriccin: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 90,
    },
    amnesia: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    kintico: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    amortiguador: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    patsalta: {
        inherit: true,
        basePower: 20,
        pp: 10,
        accuracy: 95,
    },
    deslumbrar: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 50,
    },
    dreameater: {
        inherit: true,
        basePower: 140,
        pp: 35,
        accuracy: 100,
    },
    gasvenenoso: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 90,
    },
    presa: {
        inherit: true,
        basePower: 25,
        pp: 15,
        accuracy: 80,
    },
    chupavidas: {
        inherit: true,
        basePower: 55,
        pp: 20,
        accuracy: 100,
    },
    lovelykiss: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    ataqueareo: {
        inherit: true,
        basePower: 125,
        pp: 25,
        accuracy: 100,
    },
    transform: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    burbuja: {
        inherit: true,
        basePower: 125,
        pp: 25,
        accuracy: 95,
    },
    puomareo: {
        inherit: true,
        basePower: 50,
        pp: 15,
        accuracy: 100,
    },
    spore: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    destello: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 75,
    },
    psicoonda: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 100,
    },
    salpicadura: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    armadcida: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 0,
    },
    martillazo: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 100,
    },
    explosin: {
        inherit: true,
        basePower: 75,
        pp: 25,
        accuracy: 85,
    },
    golpesfuria: {
        inherit: true,
        basePower: 30,
        pp: 20,
        accuracy: 75,
    },
    huesomerang: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 80,
    },
    descanso: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    avalancha: {
        inherit: true,
        basePower: 95,
        pp: 15,
        accuracy: 100,
    },
    hipcolmillo: {
        inherit: true,
        basePower: 35,
        pp: 15,
        accuracy: 100,
    },
    afilar: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    conversin: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    triataque: {
        inherit: true,
        basePower: 80,
        pp: 30,
        accuracy: 100,
    },
    superdiente: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 100,
    },
    cuchillada: {
        inherit: true,
        basePower: 30,
        pp: 20,
        accuracy: 95,
    },
    substitute: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    combate: {
        inherit: true,
        basePower: 50,
        pp: 1,
        accuracy: 100,
    },
    esquema: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    triplepatada: {
        inherit: true,
        basePower: 20,
        pp: 20,
        accuracy: 100,
    },
    ladrn: {
        inherit: true,
        basePower: 50,
        pp: 40,
        accuracy: 95,
    },
    telaraa: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 85,
    },
    telpata: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 55,
    },
    pesadilla: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    ruedafuego: {
        inherit: true,
        basePower: 85,
        pp: 25,
        accuracy: 90,
    },
    ronquido: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 100,
    },
    maldicin: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    azote: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 90,
    },
    conversin: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    aerochorro: {
        inherit: true,
        basePower: 105,
        pp: 20,
        accuracy: 80,
    },
    esporagodn: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 80,
    },
    inversin: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 75,
    },
    rencor: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    nievepolvo: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 100,
    },
    proteccin: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    ultrapuo: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 95,
    },
    carasusto: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    finta: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 0,
    },
    besodulce: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    tambor: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 0,
    },
    bombalodo: {
        inherit: true,
        basePower: 50,
        pp: 5,
        accuracy: 100,
    },
    bofetnlodo: {
        inherit: true,
        basePower: 60,
        pp: 20,
        accuracy: 100,
    },
    pulpocan: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 100,
    },
    pas: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 0,
    },
    electrocan: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 45,
    },
    profeca: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    mismodestino: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    cantomortal: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    vientohielo: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 95,
    },
    detect: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    ataqueseo: {
        inherit: true,
        basePower: 20,
        pp: 20,
        accuracy: 70,
    },
    fijarblanco: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    enfado: {
        inherit: true,
        basePower: 90,
        pp: 15,
        accuracy: 95,
    },
    tormarena: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    gigadrenado: {
        inherit: true,
        basePower: 35,
        pp: 20,
        accuracy: 90,
    },
    aguante: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    encanto: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    desenrollar: {
        inherit: true,
        basePower: 65,
        pp: 35,
        accuracy: 100,
    },
    falsotortazo: {
        inherit: true,
        basePower: 85,
        pp: 35,
        accuracy: 85,
    },
    contoneo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    milkdrink: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    chispa: {
        inherit: true,
        basePower: 85,
        pp: 35,
        accuracy: 90,
    },
    cortefuria: {
        inherit: true,
        basePower: 65,
        pp: 15,
        accuracy: 90,
    },
    aladeacero: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 100,
    },
    maldeojo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    atraccin: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    sonmbulo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    campanacura: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 0,
    },
    retroceso: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 95,
    },
    presente: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 60,
    },
    frustracin: {
        inherit: true,
        basePower: 1,
        pp: 40,
        accuracy: 85,
    },
    velosagrado: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    dividedolor: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 90,
    },
    sacredfire: {
        inherit: true,
        basePower: 200,
        pp: 40,
        accuracy: 95,
    },
    magnitud: {
        inherit: true,
        basePower: 1,
        pp: 15,
        accuracy: 95,
    },
    puodinmico: {
        inherit: true,
        basePower: 65,
        pp: 25,
        accuracy: 35,
    },
    megacuerno: {
        inherit: true,
        basePower: 90,
        pp: 15,
        accuracy: 80,
    },
    dragoaliento: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 100,
    },
    batonpass: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    otravez: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    pursuit: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 95,
    },
    rapidspin: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 100,
    },
    dulcearoma: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 95,
    },
    colafrrea: {
        inherit: true,
        basePower: 70,
        pp: 15,
        accuracy: 75,
    },
    garrametal: {
        inherit: true,
        basePower: 125,
        pp: 20,
        accuracy: 100,
    },
    tirovital: {
        inherit: true,
        basePower: 85,
        pp: 20,
        accuracy: 100,
    },
    solmatinal: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    sntesis: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 0,
    },
    luzlunar: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    poderoculto: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 95,
    },
    tajocruzado: {
        inherit: true,
        basePower: 55,
        pp: 30,
        accuracy: 95,
    },
    cicln: {
        inherit: true,
        basePower: 75,
        pp: 25,
        accuracy: 90,
    },
    danzalluvia: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    dasoleado: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    triturar: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 100,
    },
    mantoespejo: {
        inherit: true,
        basePower: 1,
        pp: 40,
        accuracy: 100,
    },
    mspsique: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    velextrema: {
        inherit: true,
        basePower: 85,
        pp: 20,
        accuracy: 90,
    },
    poderpasado: {
        inherit: true,
        basePower: 55,
        pp: 20,
        accuracy: 100,
    },
    bolasombra: {
        inherit: true,
        basePower: 95,
        pp: 40,
        accuracy: 100,
    },
    premonicin: {
        inherit: true,
        basePower: 95,
        pp: 20,
        accuracy: 100,
    },
    golperoca: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 100,
    },
    torbellino: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 100,
    },
    beatup: {
        inherit: true,
        basePower: 125,
        pp: 40,
        accuracy: 100,
    },
    sorpresa: {
        inherit: true,
        basePower: 65,
        pp: 30,
        accuracy: 90,
    },
    alboroto: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 80,
    },
    reserva: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 0,
    },
    escupir: {
        inherit: true,
        basePower: 95,
        pp: 5,
        accuracy: 100,
    },
    tragar: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    ondagnea: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 100,
    },
    granizo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    tormento: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 75,
    },
    camelo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    fuegofatuo: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 95,
    },
    legado: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    imagen: {
        inherit: true,
        basePower: 60,
        pp: 20,
        accuracy: 100,
    },
    puocertero: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 100,
    },
    estmulo: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 100,
    },
    seuelo: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 75,
    },
    adaptacin: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    carga: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    mofa: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    refuerzo: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 95,
    },
    truco: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 75,
    },
    imitacin: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    deseo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    ayuda: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    arraigo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 80,
    },
    fuerzabruta: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 95,
    },
    capamgica: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 85,
    },
    reciclaje: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 85,
    },
    desquite: {
        inherit: true,
        basePower: 70,
        pp: 30,
        accuracy: 80,
    },
    demolicin: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 100,
    },
    bostezo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    desarme: {
        inherit: true,
        basePower: 55,
        pp: 5,
        accuracy: 100,
    },
    esfuerzo: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 100,
    },
    estallido: {
        inherit: true,
        basePower: 25,
        pp: 15,
        accuracy: 95,
    },
    intercambio: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    cerca: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 80,
    },
    alivio: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    rabia: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    robo: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 95,
    },
    daosecreto: {
        inherit: true,
        basePower: 115,
        pp: 20,
        accuracy: 85,
    },
    buceo: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 95,
    },
    empujn: {
        inherit: true,
        basePower: 20,
        pp: 40,
        accuracy: 85,
    },
    camuflaje: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 70,
    },
    tailglow: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 80,
    },
    resplandor: {
        inherit: true,
        basePower: 85,
        pp: 20,
        accuracy: 95,
    },
    bolaneblina: {
        inherit: true,
        basePower: 35,
        pp: 20,
        accuracy: 100,
    },
    danzapluma: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    danzacaos: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 90,
    },
    patadagnea: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 75,
    },
    chapoteolodo: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 95,
    },
    bolahielo: {
        inherit: true,
        basePower: 70,
        pp: 5,
        accuracy: 75,
    },
    brazopincho: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 100,
    },
    relajo: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    vozarrn: {
        inherit: true,
        basePower: 70,
        pp: 15,
        accuracy: 100,
    },
    colmilloven: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 100,
    },
    garrabrutal: {
        inherit: true,
        basePower: 95,
        pp: 20,
        accuracy: 100,
    },
    anillogneo: {
        inherit: true,
        basePower: 95,
        pp: 25,
        accuracy: 60,
    },
    hidrocan: {
        inherit: true,
        basePower: 70,
        pp: 25,
        accuracy: 100,
    },
    puometeoro: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 80,
    },
    impresionar: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 100,
    },
    meteorobola: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 100,
    },
    aromatherapy: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    llantofalso: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    aireafilado: {
        inherit: true,
        basePower: 30,
        pp: 5,
        accuracy: 85,
    },
    sofoco: {
        inherit: true,
        basePower: 35,
        pp: 20,
        accuracy: 85,
    },
    rastreo: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    tumbarocas: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 100,
    },
    vientoplata: {
        inherit: true,
        basePower: 50,
        pp: 10,
        accuracy: 75,
    },
    ecometlico: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 85,
    },
    silbato: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 85,
    },
    cosquillas: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    masacsmica: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    salpicar: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 100,
    },
    doblerayo: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 100,
    },
    puosombra: {
        inherit: true,
        basePower: 85,
        pp: 25,
        accuracy: 0,
    },
    paranormal: {
        inherit: true,
        basePower: 70,
        pp: 25,
        accuracy: 90,
    },
    ganchoalto: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 85,
    },
    buclearena: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 90,
    },
    fropolar: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 45,
    },
    agualodosa: {
        inherit: true,
        basePower: 80,
        pp: 15,
        accuracy: 80,
    },
    recurrente: {
        inherit: true,
        basePower: 25,
        pp: 20,
        accuracy: 65,
    },
    golpeareo: {
        inherit: true,
        basePower: 75,
        pp: 25,
        accuracy: 0,
    },
    carmbano: {
        inherit: true,
        basePower: 30,
        pp: 35,
        accuracy: 95,
    },
    deffrrea: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    bloqueo: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    aullido: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    garradragn: {
        inherit: true,
        basePower: 20,
        pp: 25,
        accuracy: 95,
    },
    plantaferoz: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 95,
    },
    corpulencia: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 0,
    },
    bote: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 70,
    },
    displodo: {
        inherit: true,
        basePower: 55,
        pp: 40,
        accuracy: 80,
    },
    colaveneno: {
        inherit: true,
        basePower: 90,
        pp: 10,
        accuracy: 90,
    },
    antojo: {
        inherit: true,
        basePower: 85,
        pp: 20,
        accuracy: 100,
    },
    placajeelc: {
        inherit: true,
        basePower: 60,
        pp: 20,
        accuracy: 85,
    },
    hojamgica: {
        inherit: true,
        basePower: 65,
        pp: 10,
        accuracy: 0,
    },
    hidrochorro: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 85,
    },
    pazmental: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    hojaaguda: {
        inherit: true,
        basePower: 40,
        pp: 20,
        accuracy: 100,
    },
    dragondance: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    pedrada: {
        inherit: true,
        basePower: 25,
        pp: 25,
        accuracy: 100,
    },
    ondavoltio: {
        inherit: true,
        basePower: 115,
        pp: 25,
        accuracy: 0,
    },
    hidropulso: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 95,
    },
    deseooculto: {
        inherit: true,
        basePower: 105,
        pp: 15,
        accuracy: 80,
    },
    psicoataque: {
        inherit: true,
        basePower: 65,
        pp: 25,
        accuracy: 95,
    }
};