export const Moves: {[k: string]: ModdedMoveData} = {
    pound: {
        inherit: true,
        basePower: 100,
        pp: 40,
        accuracy: 100,
    },
    karatechop: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 100,
    },
    doubleslap: {
        inherit: true,
        basePower: 30,
        pp: 20,
        accuracy: 40,
    },
    cometpunch: {
        inherit: true,
        basePower: 30,
        pp: 25,
        accuracy: 80,
    },
    megapunch: {
        inherit: true,
        basePower: 50,
        pp: 30,
        accuracy: 65,
    },
    payday: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 90,
    },
    firepunch: {
        inherit: true,
        basePower: 90,
        pp: 15,
        accuracy: 100,
    },
    icepunch: {
        inherit: true,
        basePower: 65,
        pp: 40,
        accuracy: 100,
    },
    thunderpunch: {
        inherit: true,
        basePower: 100,
        pp: 20,
        accuracy: 90,
    },
    scratch: {
        inherit: true,
        basePower: 100,
        pp: 20,
        accuracy: 95,
    },
    vicegrip: {
        inherit: true,
        basePower: 65,
        pp: 10,
        accuracy: 90,
    },
    guillotine: {
        inherit: true,
        basePower: 1,
        pp: 30,
        accuracy: 30,
    },
    razorwind: {
        inherit: true,
        basePower: 95,
        pp: 25,
        accuracy: 95,
    },
    swordsdance: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    cut: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 100,
    },
    gust: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 90,
    },
    wingattack: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 95,
    },
    whirlwind: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    fly: {
        inherit: true,
        basePower: 55,
        pp: 20,
        accuracy: 90,
    },
    bind: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 80,
    },
    slam: {
        inherit: true,
        basePower: 125,
        pp: 40,
        accuracy: 75,
    },
    vinewhip: {
        inherit: true,
        basePower: 65,
        pp: 25,
        accuracy: 95,
    },
    stomp: {
        inherit: true,
        basePower: 95,
        pp: 40,
        accuracy: 75,
    },
    doublekick: {
        inherit: true,
        basePower: 25,
        pp: 25,
        accuracy: 100,
    },
    megakick: {
        inherit: true,
        basePower: 85,
        pp: 25,
        accuracy: 70,
    },
    jumpkick: {
        inherit: true,
        basePower: 95,
        pp: 15,
        accuracy: 80,
    },
    rollingkick: {
        inherit: true,
        basePower: 65,
        pp: 35,
        accuracy: 65,
    },
    sandattack: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    headbutt: {
        inherit: true,
        basePower: 55,
        pp: 20,
        accuracy: 90,
    },
    hornattack: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 90,
    },
    furyattack: {
        inherit: true,
        basePower: 30,
        pp: 40,
        accuracy: 100,
    },
    horndrill: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 35,
    },
    tackle: {
        inherit: true,
        basePower: 145,
        pp: 25,
        accuracy: 100,
    },
    bodyslam: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 100,
    },
    wrap: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 95,
    },
    takedown: {
        inherit: true,
        basePower: 95,
        pp: 30,
        accuracy: 95,
    },
    thrash: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 95,
    },
    doubleedge: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 100,
    },
    tailwhip: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 100,
    },
    poisonsting: {
        inherit: true,
        basePower: 55,
        pp: 5,
        accuracy: 100,
    },
    twineedle: {
        inherit: true,
        basePower: 35,
        pp: 20,
        accuracy: 100,
    },
    pinmissile: {
        inherit: true,
        basePower: 30,
        pp: 30,
        accuracy: 95,
    },
    leer: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    bite: {
        inherit: true,
        basePower: 135,
        pp: 20,
        accuracy: 95,
    },
    growl: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 85,
    },
    roar: {
        inherit: true,
        basePower: 0,
        pp: 30,
        accuracy: 100,
    },
    sing: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    supersonic: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    sonicboom: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 95,
    },
    disable: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    acid: {
        inherit: true,
        basePower: 95,
        pp: 20,
        accuracy: 100,
    },
    ember: {
        inherit: true,
        basePower: 25,
        pp: 20,
        accuracy: 95,
    },
    flamethrower: {
        inherit: true,
        basePower: 75,
        pp: 20,
        accuracy: 95,
    },
    mist: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    watergun: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 60,
    },
    hydropump: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 55,
    },
    surf: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 100,
    },
    icebeam: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 95,
    },
    blizzard: {
        inherit: true,
        basePower: 75,
        pp: 25,
        accuracy: 45,
    },
    psybeam: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 100,
    },
    bubblebeam: {
        inherit: true,
        basePower: 70,
        pp: 5,
        accuracy: 90,
    },
    aurorabeam: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 75,
    },
    hyperbeam: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 85,
    },
    peck: {
        inherit: true,
        basePower: 90,
        pp: 35,
        accuracy: 95,
    },
    drillpeck: {
        inherit: true,
        basePower: 75,
        pp: 25,
        accuracy: 100,
    },
    submission: {
        inherit: true,
        basePower: 105,
        pp: 20,
        accuracy: 70,
    },
    lowkick: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 100,
    },
    counter: {
        inherit: true,
        basePower: 1,
        pp: 10,
        accuracy: 80,
    },
    seismictoss: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 100,
    },
    strength: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 95,
    },
    absorb: {
        inherit: true,
        basePower: 70,
        pp: 25,
        accuracy: 100,
    },
    megadrain: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 90,
    },
    leechseed: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    growth: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    razorleaf: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 70,
    },
    solarbeam: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 100,
    },
    poisonpowder: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 85,
    },
    stunspore: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 35,
    },
    sleeppowder: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 60,
    },
    petaldance: {
        inherit: true,
        basePower: 85,
        pp: 40,
        accuracy: 75,
    },
    stringshot: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 80,
    },
    dragonrage: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 90,
    },
    firespin: {
        inherit: true,
        basePower: 130,
        pp: 20,
        accuracy: 100,
    },
    thundershock: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 100,
    },
    thunderbolt: {
        inherit: true,
        basePower: 90,
        pp: 15,
        accuracy: 75,
    },
    thunderwave: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    thunder: {
        inherit: true,
        basePower: 125,
        pp: 20,
        accuracy: 100,
    },
    rockthrow: {
        inherit: true,
        basePower: 85,
        pp: 15,
        accuracy: 95,
    },
    earthquake: {
        inherit: true,
        basePower: 85,
        pp: 10,
        accuracy: 95,
    },
    fissure: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 20,
    },
    dig: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 100,
    },
    toxic: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    confusion: {
        inherit: true,
        basePower: 85,
        pp: 25,
        accuracy: 100,
    },
    psychic: {
        inherit: true,
        basePower: 45,
        pp: 15,
        accuracy: 95,
    },
    hypnosis: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 65,
    },
    meditate: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    agility: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 0,
    },
    quickattack: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 100,
    },
    rage: {
        inherit: true,
        basePower: 135,
        pp: 20,
        accuracy: 90,
    },
    teleport: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    nightshade: {
        inherit: true,
        basePower: 1,
        pp: 15,
        accuracy: 100,
    },
    mimic: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    screech: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 100,
    },
    doubleteam: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 0,
    },
    recover: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    harden: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    minimize: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    smokescreen: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 85,
    },
    confuseray: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    withdraw: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    defensecurl: {
        inherit: true,
        basePower: 0,
        pp: 40,
        accuracy: 0,
    },
    barrier: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    lightscreen: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    haze: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    reflect: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    focusenergy: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    bide: {
        inherit: true,
        basePower: 1,
        pp: 30,
        accuracy: 90,
    },
    metronome: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    mirrormove: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    selfdestruct: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 90,
    },
    eggbomb: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 45,
    },
    lick: {
        inherit: true,
        basePower: 115,
        pp: 20,
        accuracy: 80,
    },
    smog: {
        inherit: true,
        basePower: 105,
        pp: 40,
        accuracy: 90,
    },
    sludge: {
        inherit: true,
        basePower: 125,
        pp: 5,
        accuracy: 85,
    },
    boneclub: {
        inherit: true,
        basePower: 70,
        pp: 30,
        accuracy: 95,
    },
    fireblast: {
        inherit: true,
        basePower: 90,
        pp: 15,
        accuracy: 85,
    },
    waterfall: {
        inherit: true,
        basePower: 100,
        pp: 5,
        accuracy: 95,
    },
    clamp: {
        inherit: true,
        basePower: 60,
        pp: 15,
        accuracy: 85,
    },
    swift: {
        inherit: true,
        basePower: 90,
        pp: 25,
        accuracy: 0,
    },
    skullbash: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 100,
    },
    spikecannon: {
        inherit: true,
        basePower: 45,
        pp: 5,
        accuracy: 90,
    },
    constrict: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 100,
    },
    amnesia: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    kinesis: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 45,
    },
    softboiled: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 90,
    },
    hijumpkick: {
        inherit: true,
        basePower: 55,
        pp: 20,
        accuracy: 95,
    },
    glare: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    dreameater: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 95,
    },
    poisongas: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    barrage: {
        inherit: true,
        basePower: 5,
        pp: 15,
        accuracy: 100,
    },
    leechlife: {
        inherit: true,
        basePower: 70,
        pp: 15,
        accuracy: 100,
    },
    lovelykiss: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 65,
    },
    skyattack: {
        inherit: true,
        basePower: 85,
        pp: 20,
        accuracy: 100,
    },
    transform: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    bubble: {
        inherit: true,
        basePower: 85,
        pp: 25,
        accuracy: 100,
    },
    dizzypunch: {
        inherit: true,
        basePower: 85,
        pp: 20,
        accuracy: 45,
    },
    spore: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    flash: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 70,
    },
    psywave: {
        inherit: true,
        basePower: 1,
        pp: 5,
        accuracy: 75,
    },
    splash: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    acidarmor: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    crabhammer: {
        inherit: true,
        basePower: 60,
        pp: 30,
        accuracy: 90,
    },
    explosion: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 85,
    },
    furyswipes: {
        inherit: true,
        basePower: 30,
        pp: 30,
        accuracy: 60,
    },
    bonemerang: {
        inherit: true,
        basePower: 30,
        pp: 20,
        accuracy: 100,
    },
    rest: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    rockslide: {
        inherit: true,
        basePower: 70,
        pp: 20,
        accuracy: 90,
    },
    hyperfang: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 95,
    },
    sharpen: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    conversion: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    triattack: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 95,
    },
    superfang: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 100,
    },
    slash: {
        inherit: true,
        basePower: 90,
        pp: 10,
        accuracy: 80,
    },
    substitute: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    struggle: {
        inherit: true,
        basePower: 50,
        pp: 1,
        accuracy: 100,
    },
    sketch: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    triplekick: {
        inherit: true,
        basePower: 35,
        pp: 15,
        accuracy: 90,
    },
    thief: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 85,
    },
    spiderweb: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 95,
    },
    mindreader: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    nightmare: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 85,
    },
    flamewheel: {
        inherit: true,
        basePower: 35,
        pp: 20,
        accuracy: 70,
    },
    snore: {
        inherit: true,
        basePower: 90,
        pp: 25,
        accuracy: 95,
    },
    curse: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 0,
    },
    flail: {
        inherit: true,
        basePower: 1,
        pp: 35,
        accuracy: 90,
    },
    conversion: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    aeroblast: {
        inherit: true,
        basePower: 55,
        pp: 10,
        accuracy: 100,
    },
    cottonspore: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    reversal: {
        inherit: true,
        basePower: 1,
        pp: 15,
        accuracy: 100,
    },
    spite: {
        inherit: true,
        basePower: 0,
        pp: 35,
        accuracy: 100,
    },
    powdersnow: {
        inherit: true,
        basePower: 20,
        pp: 15,
        accuracy: 100,
    },
    protect: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    machpunch: {
        inherit: true,
        basePower: 105,
        pp: 25,
        accuracy: 90,
    },
    scaryface: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    faintattack: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 0,
    },
    sweetkiss: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    bellydrum: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    sludgebomb: {
        inherit: true,
        basePower: 95,
        pp: 15,
        accuracy: 60,
    },
    mudslap: {
        inherit: true,
        basePower: 60,
        pp: 25,
        accuracy: 90,
    },
    octazooka: {
        inherit: true,
        basePower: 60,
        pp: 20,
        accuracy: 95,
    },
    spikes: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    zapcannon: {
        inherit: true,
        basePower: 90,
        pp: 20,
        accuracy: 35,
    },
    foresight: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 90,
    },
    destinybond: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    perishsong: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    icywind: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 100,
    },
    detect: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    bonerush: {
        inherit: true,
        basePower: 30,
        pp: 25,
        accuracy: 90,
    },
    lockon: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    outrage: {
        inherit: true,
        basePower: 140,
        pp: 15,
        accuracy: 95,
    },
    sandstorm: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    gigadrain: {
        inherit: true,
        basePower: 80,
        pp: 15,
        accuracy: 95,
    },
    endure: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    charm: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    rollout: {
        inherit: true,
        basePower: 20,
        pp: 25,
        accuracy: 95,
    },
    falseswipe: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 75,
    },
    swagger: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 85,
    },
    milkdrink: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    spark: {
        inherit: true,
        basePower: 95,
        pp: 25,
        accuracy: 95,
    },
    furycutter: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 95,
    },
    steelwing: {
        inherit: true,
        basePower: 20,
        pp: 40,
        accuracy: 100,
    },
    meanlook: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    attract: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 85,
    },
    sleeptalk: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    healbell: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    return: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 95,
    },
    present: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 100,
    },
    frustration: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 95,
    },
    safeguard: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    painsplit: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 65,
    },
    sacredfire: {
        inherit: true,
        basePower: 70,
        pp: 5,
        accuracy: 95,
    },
    magnitude: {
        inherit: true,
        basePower: 1,
        pp: 10,
        accuracy: 95,
    },
    dynamicpunch: {
        inherit: true,
        basePower: 110,
        pp: 20,
        accuracy: 45,
    },
    megahorn: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 95,
    },
    dragonbreath: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 100,
    },
    batonpass: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    encore: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    pursuit: {
        inherit: true,
        basePower: 50,
        pp: 15,
        accuracy: 100,
    },
    rapidspin: {
        inherit: true,
        basePower: 65,
        pp: 15,
        accuracy: 90,
    },
    sweetscent: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 95,
    },
    irontail: {
        inherit: true,
        basePower: 125,
        pp: 20,
        accuracy: 95,
    },
    metalclaw: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 85,
    },
    vitalthrow: {
        inherit: true,
        basePower: 90,
        pp: 25,
        accuracy: 100,
    },
    morningsun: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    synthesis: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    moonlight: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    hiddenpower: {
        inherit: true,
        basePower: 1,
        pp: 30,
        accuracy: 90,
    },
    crosschop: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 70,
    },
    twister: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 100,
    },
    raindance: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    sunnyday: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 0,
    },
    crunch: {
        inherit: true,
        basePower: 70,
        pp: 25,
        accuracy: 80,
    },
    mirrorcoat: {
        inherit: true,
        basePower: 1,
        pp: 15,
        accuracy: 100,
    },
    psychup: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    extremespeed: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 100,
    },
    ancientpower: {
        inherit: true,
        basePower: 100,
        pp: 25,
        accuracy: 90,
    },
    shadowball: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 100,
    },
    futuresight: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 100,
    },
    rocksmash: {
        inherit: true,
        basePower: 105,
        pp: 25,
        accuracy: 100,
    },
    whirlpool: {
        inherit: true,
        basePower: 100,
        pp: 20,
        accuracy: 100,
    },
    beatup: {
        inherit: true,
        basePower: 80,
        pp: 5,
        accuracy: 90,
    },
    fakeout: {
        inherit: true,
        basePower: 120,
        pp: 20,
        accuracy: 85,
    },
    uproar: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 100,
    },
    stockpile: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    spitup: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 95,
    },
    swallow: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    heatwave: {
        inherit: true,
        basePower: 70,
        pp: 25,
        accuracy: 100,
    },
    hail: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    torment: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    flatter: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    willowisp: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 50,
    },
    memento: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    facade: {
        inherit: true,
        basePower: 100,
        pp: 35,
        accuracy: 95,
    },
    focuspunch: {
        inherit: true,
        basePower: 60,
        pp: 20,
        accuracy: 100,
    },
    smellingsalt: {
        inherit: true,
        basePower: 85,
        pp: 35,
        accuracy: 100,
    },
    followme: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 70,
    },
    naturepower: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 90,
    },
    charge: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    taunt: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    helpinghand: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    trick: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 95,
    },
    roleplay: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 80,
    },
    wish: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 95,
    },
    assist: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    ingrain: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    superpower: {
        inherit: true,
        basePower: 75,
        pp: 25,
        accuracy: 95,
    },
    magiccoat: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    recycle: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 90,
    },
    revenge: {
        inherit: true,
        basePower: 80,
        pp: 20,
        accuracy: 90,
    },
    brickbreak: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 100,
    },
    yawn: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 75,
    },
    knockoff: {
        inherit: true,
        basePower: 75,
        pp: 15,
        accuracy: 100,
    },
    endeavor: {
        inherit: true,
        basePower: 1,
        pp: 20,
        accuracy: 95,
    },
    eruption: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 80,
    },
    skillswap: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 100,
    },
    imprison: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    refresh: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 65,
    },
    grudge: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    snatch: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 90,
    },
    secretpower: {
        inherit: true,
        basePower: 80,
        pp: 15,
        accuracy: 100,
    },
    dive: {
        inherit: true,
        basePower: 65,
        pp: 15,
        accuracy: 85,
    },
    armthrust: {
        inherit: true,
        basePower: 30,
        pp: 5,
        accuracy: 90,
    },
    camouflage: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 95,
    },
    tailglow: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    lusterpurge: {
        inherit: true,
        basePower: 95,
        pp: 20,
        accuracy: 100,
    },
    mistball: {
        inherit: true,
        basePower: 115,
        pp: 25,
        accuracy: 100,
    },
    featherdance: {
        inherit: true,
        basePower: 0,
        pp: 10,
        accuracy: 75,
    },
    teeterdance: {
        inherit: true,
        basePower: 0,
        pp: 5,
        accuracy: 90,
    },
    blazekick: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 75,
    },
    mudsport: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 95,
    },
    iceball: {
        inherit: true,
        basePower: 95,
        pp: 25,
        accuracy: 85,
    },
    needlearm: {
        inherit: true,
        basePower: 80,
        pp: 25,
        accuracy: 90,
    },
    slackoff: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 80,
    },
    hypervoice: {
        inherit: true,
        basePower: 125,
        pp: 25,
        accuracy: 95,
    },
    poisonfang: {
        inherit: true,
        basePower: 75,
        pp: 5,
        accuracy: 90,
    },
    crushclaw: {
        inherit: true,
        basePower: 115,
        pp: 20,
        accuracy: 95,
    },
    blastburn: {
        inherit: true,
        basePower: 90,
        pp: 5,
        accuracy: 100,
    },
    hydrocannon: {
        inherit: true,
        basePower: 95,
        pp: 20,
        accuracy: 90,
    },
    meteormash: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 95,
    },
    astonish: {
        inherit: true,
        basePower: 55,
        pp: 20,
        accuracy: 90,
    },
    weatherball: {
        inherit: true,
        basePower: 145,
        pp: 15,
        accuracy: 100,
    },
    aromatherapy: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    faketears: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    aircutter: {
        inherit: true,
        basePower: 50,
        pp: 20,
        accuracy: 90,
    },
    overheat: {
        inherit: true,
        basePower: 55,
        pp: 10,
        accuracy: 85,
    },
    odorsleuth: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    rocktomb: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 85,
    },
    silverwind: {
        inherit: true,
        basePower: 155,
        pp: 40,
        accuracy: 95,
    },
    metalsound: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 65,
    },
    grasswhistle: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 55,
    },
    tickle: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 100,
    },
    cosmicpower: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    waterspout: {
        inherit: true,
        basePower: 125,
        pp: 15,
        accuracy: 100,
    },
    signalbeam: {
        inherit: true,
        basePower: 50,
        pp: 30,
        accuracy: 100,
    },
    shadowpunch: {
        inherit: true,
        basePower: 55,
        pp: 15,
        accuracy: 0,
    },
    extrasensory: {
        inherit: true,
        basePower: 30,
        pp: 25,
        accuracy: 100,
    },
    skyuppercut: {
        inherit: true,
        basePower: 90,
        pp: 25,
        accuracy: 100,
    },
    sandtomb: {
        inherit: true,
        basePower: 100,
        pp: 15,
        accuracy: 100,
    },
    sheercold: {
        inherit: true,
        basePower: 1,
        pp: 25,
        accuracy: 25,
    },
    muddywater: {
        inherit: true,
        basePower: 125,
        pp: 15,
        accuracy: 90,
    },
    bulletseed: {
        inherit: true,
        basePower: 40,
        pp: 40,
        accuracy: 100,
    },
    aerialace: {
        inherit: true,
        basePower: 95,
        pp: 15,
        accuracy: 0,
    },
    iciclespear: {
        inherit: true,
        basePower: 25,
        pp: 15,
        accuracy: 100,
    },
    irondefense: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    block: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 100,
    },
    howl: {
        inherit: true,
        basePower: 0,
        pp: 20,
        accuracy: 0,
    },
    dragonclaw: {
        inherit: true,
        basePower: 50,
        pp: 40,
        accuracy: 95,
    },
    frenzyplant: {
        inherit: true,
        basePower: 90,
        pp: 35,
        accuracy: 100,
    },
    bulkup: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 0,
    },
    bounce: {
        inherit: true,
        basePower: 50,
        pp: 15,
        accuracy: 60,
    },
    mudshot: {
        inherit: true,
        basePower: 65,
        pp: 15,
        accuracy: 95,
    },
    poisontail: {
        inherit: true,
        basePower: 50,
        pp: 25,
        accuracy: 80,
    },
    covet: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 100,
    },
    volttackle: {
        inherit: true,
        basePower: 95,
        pp: 25,
        accuracy: 100,
    },
    magicalleaf: {
        inherit: true,
        basePower: 55,
        pp: 25,
        accuracy: 0,
    },
    watersport: {
        inherit: true,
        basePower: 0,
        pp: 15,
        accuracy: 90,
    },
    calmmind: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    leafblade: {
        inherit: true,
        basePower: 100,
        pp: 30,
        accuracy: 100,
    },
    dragondance: {
        inherit: true,
        basePower: 0,
        pp: 25,
        accuracy: 0,
    },
    rockblast: {
        inherit: true,
        basePower: 30,
        pp: 25,
        accuracy: 50,
    },
    shockwave: {
        inherit: true,
        basePower: 25,
        pp: 15,
        accuracy: 0,
    },
    waterpulse: {
        inherit: true,
        basePower: 65,
        pp: 20,
        accuracy: 95,
    },
    doomdesire: {
        inherit: true,
        basePower: 90,
        pp: 35,
        accuracy: 95,
    },
    psychoboost: {
        inherit: true,
        basePower: 65,
        pp: 10,
        accuracy: 95,
    }
};